// US-129 Gate 1 C2: every name a turn file may use, and what it means -
// rendered from the library entries' own `doc` lines, so the listing and
// docs/JEV_LIBRARY.md cannot drift from the code.
import { genericLibrary } from './library.mjs';
import { ginLibrary } from '../gin/library.mjs';
import { rtgLibrary } from '../rtg/library.mjs';

/**
 * Every library, built with no table behind it - only its names and docs
 * are read.
 */
export function allLibraries() {
  return [
    { title: 'Generic', library: genericLibrary({}) },
    { title: 'rtg', library: rtgLibrary({ name: 'doc' }) },
    { title: 'gin', library: ginLibrary({}) },
  ];
}

const HEADER = `# The Jev player library

Generated by \`bobp make jev-library-doc\` from the library's own entries
(\`tools/jevLibrary.mjs\`) - do not edit by hand; a test fails when this
file is stale.

A game's turn file (\`games/<game>/turn.yaml\`, US-129/D154) is an XState
v5 statechart whose guards, actions and actors are the names below. A
name the library does not have is refused when the file loads.

**Events** the seat sends: \`TABLE\` (every look at the table, carrying
\`changed\`, \`quietFor\`, \`heard\`), \`STEP\` (take one step), \`QUIT\`
(asked to leave).

**Tags** the author writes: \`move\` (it is this bot's move here) and
\`safe\` (a bot asked to leave may leave from here; at least one must be
reachable). \`busy\` is added by the interpreter to every state that
invokes an actor. A \`type: final\` state ends the run.

**Parameters** go in \`params\` (guards, actions) or \`with\` (actors);
the names in backticks in each line below are the ones it reads.
`;

/**
 * The whole document, as markdown.
 */
export function renderLibraryDocument() {
  const sections = allLibraries().map(({ title, library }) => {
    const kinds = Object.entries(library).filter(([, entries]) => Object.keys(entries).length > 0);
    const parts = kinds.map(([kind, entries]) => {
      const lines = Object.entries(entries).map(([name, entry]) => `- \`${name}\` - ${entry.doc}`);
      return `### ${kind}\n\n${lines.join('\n')}`;
    });
    return `## ${title}\n\n${parts.join('\n\n')}`;
  });
  return `${HEADER}\n${sections.join('\n\n')}\n`;
}
