/**
 * Recard the Gathering — YAML → ES-module catalog compiler (US-75, D77).
 *
 * The I/O shell around `cardSchema.mjs`'s pure validation. Reads every
 * authored pool under `content/rtg/cards/`, validates it, derives each
 * card's `cmc`/`colors` from its cost, and writes one committed
 * `src/decks/rtg/catalog.js` that the app and every tool import.
 *
 * The app never reads YAML and never imports this file - that split is
 * what keeps `yaml` a devDependency rather than a runtime one, and what
 * keeps a malformed pool a BUILD failure rather than a broken table.
 *
 * Output goes to `src/decks/rtg/`, not `build/` - `build/` is gitignored
 * and this artifact must ship with the app.
 *
 * Usage: `npm run cards:build`
 */
import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse } from 'yaml';

import { parseManaCost, validateCardPool } from './cardSchema.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const CARDS_DIR = path.join(ROOT, 'content/rtg/cards');
const DECKS_DIR = path.join(ROOT, 'content/rtg/decks');
// An ES MODULE, not JSON: the browser imports this directly (no fetch,
// no JSON import assertion) and so does every Node tool, which keeps ONE
// compiled artifact rather than a .json for tooling plus a .js for the
// app that could drift apart.
const OUT_FILE = path.join(ROOT, 'src/decks/rtg/catalog.js');

/**
 * Read every `*.yaml` file in a directory as one concatenated list.
 */
async function readYamlList(directory) {
  let entries;
  try {
    entries = await readdir(directory);
  } catch {
    return [];
  }
  const names = entries.filter((name) => name.endsWith('.yaml')).toSorted((a, b) => a.localeCompare(b));
  const items = [];
  for (const name of names) {
    const parsed = parse(await readFile(path.join(directory, name), 'utf8'));
    if (!Array.isArray(parsed)) throw new TypeError(`${name}: expected a top-level list`);
    items.push(...parsed);
  }
  return items;
}

/** Read every `*.yaml` pool file, newest-authored order irrelevant -
 * the pool is keyed by id, and `validateCardPool` is what catches a
 * collision between two files. */
async function readPools(directory) {
  const entries = await readdir(directory);
  const names = entries.filter((name) => name.endsWith('.yaml')).toSorted((a, b) => a.localeCompare(b));
  const cards = [];
  for (const name of names) {
    const raw = await readFile(path.join(directory, name), 'utf8');
    const parsed = parse(raw);
    if (!Array.isArray(parsed)) {
      throw new TypeError(`${name}: expected a top-level list of cards, got ${typeof parsed}`);
    }
    // `source` is carried only for error messages - stripped before the
    // card is written, so it never reaches the app.
    for (const card of parsed) cards.push({ ...card, source: name });
  }
  return cards;
}

/** Derive what must never be authored by hand (D77): `cmc` and `colors`
 * come from the cost string, so a card's curve position can't drift
 * from its own printed cost. */
function deriveCard({ source, ...card }) {
  // `symbols` is stamped here too so the browser never needs a second
  // mana-cost parser: `parseManaCost` already computed the symbol
  // sequence while validating, and a display-side reimplementation is
  // exactly how a cost and its rendered pips drift apart.
  const { cmc, colors, symbols } = parseManaCost(card.cost ?? '');
  return { ...card, cost: card.cost ?? '', cmc, colors, symbols, face: 'rtg' };
}

async function main() {
  const authored = await readPools(CARDS_DIR);
  const errors = validateCardPool(authored.map(({ source, ...card }) => card));

  if (errors.length > 0) {
    console.error(`cards:build — ${errors.length} validation error(s):\n`);
    for (const error of errors) console.error(`  ✖ ${error}`);
    process.exitCode = 1;
    return;
  }

  const cards = authored.map((card) => deriveCard(card));
  const decks = await readYamlList(DECKS_DIR);

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, [
    '// GENERATED by `npm run cards:build` from content/rtg/**.yaml — do not edit.',
    '// The authored YAML is the source of truth; this is the compiled artifact',
    '// the app imports and every tool reads.',
    `export const CARDS = ${JSON.stringify(cards, null, 2)};`,
    '',
    `export const DECKS = ${JSON.stringify(decks, null, 2)};`,
    '',
  ].join('\n'));
  console.log(`cards:build — ${cards.length} card(s), ${decks.length} deck(s) → ${path.relative(ROOT, OUT_FILE)}`);
}

await main();
